In [15]:
import numpy as np
zero = np.zeros(6)
zero

array([0., 0., 0., 0., 0., 0.])

In [16]:
zero[3] = 1
zero

array([0., 0., 0., 1., 0., 0.])

In [53]:
import numpy as np

class Solution(object):
    def commonChars(self, A):
        """
        :type A: List[str]
        :rtype: List[str]
        """
        ret = []
        d_ret = {}
        n_word = len(A)
        for i, word in enumerate(A):
            for j, a in enumerate(word):
                if a in d_ret.keys():
                    d_ret[a][i] += 1
                else:
                    zero = np.zeros(n_word)
                    zero[i] = 1
                    d_ret[a] = zero
        self.d_ret = d_ret
        
        for key, arr in d_ret.items():
            if arr.all() :
                ret += [key] * int(np.min(arr))
        
        self.ret = ret
        return ret

In [54]:
A = ["bella","label","roller"]
s = Solution()
s.commonChars(A)

['e', 'l', 'l']

In [43]:
s.d_ret

{'b': array([1., 1., 0.]),
 'e': array([1., 1., 1.]),
 'l': array([2., 2., 2.]),
 'a': array([1., 1., 0.]),
 'r': array([0., 0., 2.]),
 'o': array([0., 0., 1.])}

In [44]:
(np.diff(s.d_ret['l']) == 0).all()

True

In [45]:
s.d_ret['l'].all()

True

In [46]:


s.d_ret['r'].all()

False

In [47]:
s.d_ret['a'].all()

False

In [39]:
A = []
s = Solution()
s.commonChars(A)

[]

In [55]:
A = ['aaaaa', 'aaabb']
s = Solution()
s.commonChars(A)

['a', 'a', 'a']

In [41]:
s.d_ret

{'a': array([5., 3.]), 'b': array([0., 2.])}

# Prob 2

In [118]:
class Solution(object):
    def isValid(self, S):
        """
        :type S: str
        :rtype: bool
        """
        
        v_str = 'abc'
        s_split = S.split(v_str)
        
        changed = True
        while changed:
            s_split_2 = (''.join(s_split)).split(v_str)
#             print(len(s_split), len(s_split_2))
            print(s_split)
            print(s_split_2)
            print(len(s_split))
            print(len(s_split_2))
            print(len( ''.join(s_split)))
            print(len( ''.join(s_split_2)))
            changed = (len( ''.join(s_split)) !=  len(''.join(s_split_2)))
            print('changed', changed)
            s_split = s_split_2
            
        print(s_split)
        return ''.join(s_split) == '' 
        

In [120]:
S = "aabcbc"
s = Solution()
s.isValid(S)


['a', 'bc']
['', '']
2
2
3
0
changed True
['', '']
['']
2
1
0
0
changed False
['']


True

In [121]:
S = "abcabcababcc"
s = Solution()
s.isValid(S)


['', '', 'ab', 'c']
['', '']
4
2
3
0
changed True
['', '']
['']
2
1
0
0
changed False
['']


True

In [122]:
S = "abccba"
s = Solution()
s.isValid(S)


['', 'cba']
['cba']
2
1
3
3
changed False
['cba']


False

In [123]:
S = "cababc"
s = Solution()
s.isValid(S)


['cab', '']
['cab']
2
1
3
3
changed False
['cab']


False

In [115]:
S = "a"
s = Solution()
s.isValid(S)


['a']
['a']
1
1
changed False
['a']


False

In [119]:
S = "aaabcbcbc" # True
s = Solution()
s.isValid(S)


['aa', 'bcbc']
['a', 'bc']
2
2
6
3
changed True
['a', 'bc']
['', '']
2
2
3
0
changed True
['', '']
['']
2
1
0
0
changed False
['']


True

# Prob 3

In [124]:
class Solution(object):
    def longestOnes(self, A, K):
        """
        :type A: List[int]
        :type K: int
        :rtype: int
        """
        
        
        
        
        
        

In [198]:
A = [1,1,1,0,0,0,1,1,1,1,0]
K = 2
s = Solution()
s.longestOnes(A, K)

In [176]:
A = [0,0,1,1,0,0,1,1,1,0,1,1,0,0,0,1,1,1,1]
K = 3
s = Solution()
s.longestOnes(A, K)

In [177]:
A[1:]

[0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1]

In [211]:
run_len = {}
run_len_ = []
group_id = 0
prev = A[0]
for i, a in enumerate(A[1:]):
    key = str(group_id)
    if a == prev:
        if key in run_len:
            run_len[key][1] += 1
        else:
            run_len[key] = [a, 2]
    else:
        group_id += 1 
        key = str(group_id)
        if key not in run_len:
            run_len[key] = [a, 1]
        run_len_.append(run_len[key])
    prev = a

In [212]:
run_len_

[[0, 3], [1, 4], [0, 1]]

In [182]:
run_len

{'0': [0, 1],
 '1': [1, 1],
 '2': [0, 1],
 '3': [1, 2],
 '5': [1, 1],
 '6': [0, 2],
 '7': [1, 3]}

In [201]:
lens = []

for i, group in enumerate(run_len_):
    print(i)
    length = 0
    k_count = 0
    for j, subgroup in enumerate(run_len_[i+1:]):
        print('start with ', i+1)

        if subgroup[0] == 0:
            k_count += subgroup[0]
        
        length += subgroup[1]    
        if k_count < K:
            lens.append(length)
            print('breaking')
            break
        

0
start with  1
breaking
1
start with  2
breaking
2


In [202]:
lens

[2, 3]

In [167]:
list(val.values())[0]

3

# Prob 4

In [251]:
class Solution(object):
    
    n_merge = 0
    def mergeStones(self, stones, K):
        """
        :type stones: List[int]
        :type K: int
        :rtype: int
        """
        
        
        def merge_recursive(stones, K):
            if len(stones) == 1:
                return self.n_merge
            elif len(stones) < K:
                return -1
            
            self.n_merge += 1
            cost_stones = np.array([i for i in zip(*[np.array(stones[i:]) for i in range(K)])]).sum(axis=1)
            min_cost = np.min(cost_stones)
            i_min_cost = np.argmin(cost_stones)
            print(i_min_cost)
            new_stones = stones[:i_min_cost] + [min_cost] + stones[i_min_cost+K:]
            print(new_stones)
            merge_recursive(new_stones, K)
        
        
        merge_recursive(stones, K)

In [252]:
stones = [3,2,4,1]
K = 2
s = Solution()
s.mergeStones(stones, K)

0
[5, 4, 1]
1
[5, 5]
0
[10]


In [228]:
stones

[3, 2, 4, 1]

array([5, 6, 5])

In [225]:
reshape_stone = np.array(zip(*[(stones)[i:] for i in range(K)]))
reshape_stone

array(<zip object at 0x1170eab88>, dtype=object)

In [221]:
reshape_stone[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [227]:
A=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
>>> n=5
>>> np.array(zip(*(A[i:] for i in range(n))))


array(<zip object at 0x1170eac88>, dtype=object)