# Prob 1

In [34]:
import numpy as np
class Solution(object):
    def largestSumAfterKNegations(self, A, K):
        """
        :type A: List[int]
        :type K: int
        :rtype: int
        """
        indice = np.argsort(A)
        print('A index for sort', indice)
        min_val = A[indice[0]] 
        pointer = 0
        A[indice[0]] = -A[indice[0]]
        
        for i in range(K-1):
            if A[indice[pointer]] < A[indice[pointer+1]]:
                A[indice[pointer]] = -A[indice[pointer]]
            else:
                pointer += 1
                A[indice[pointer]] = -A[indice[pointer]]
            print('A', A)
        print('end', A)
        return sum(A)

In [35]:
A = [4,2,3]
K = 1

s = Solution()
s.largestSumAfterKNegations(A, K)

A index for sort [1 2 0]
end [4, -2, 3]


5

In [36]:
A = [3,-1,0,2]
K = 3

s = Solution()
s.largestSumAfterKNegations(A, K)

A index for sort [1 2 3 0]
A [3, 1, 0, 2]
A [3, 1, 0, 2]
end [3, 1, 0, 2]


6

In [37]:
A = [2,-3,-1,5,-4]
K = 2
s = Solution()
s.largestSumAfterKNegations(A, K)

A index for sort [4 1 2 0 3]
A [2, 3, -1, 5, 4]
end [2, 3, -1, 5, 4]


13

In [38]:

# 3
# Expected 11
A = [-2,5,0,2,-2]
K = 3
s = Solution()
s.largestSumAfterKNegations(A, K)

A index for sort [0 4 2 3 1]
A [2, 5, 0, 2, 2]
A [2, 5, 0, 2, 2]
end [2, 5, 0, 2, 2]


11

# Prob 2

In [39]:
class Solution(object):
    def clumsy(self, N):
        """
        :type N: int
        :rtype: int
        """
        
    self.d = {}
    def fa(M):
        if M not in self.d.keys():
            fa
        
        

In [40]:
N = 4
s = Solution()
s.clumsy(N)

In [136]:
d = {}
def fa(N):
    if N >= 3:
        return (N * (N -1) // (N-2))
        
    

In [138]:
fa(3)

6

In [139]:
fa(4)

6

In [140]:
fa(5)

6

In [141]:
fa(6)

7

In [142]:
fa(10)

11

# Prob 3 

In [80]:
import numpy as np
class Solution(object):
    def minDominoRotations(self, A, B):
        """
        :type A: List[int]
        :type B: List[int]
        :rtype: int
        """
        
#         AB = np.array()
        freq = np.zeros([6,6])
        for i, (a, b) in enumerate(zip(A, B)):
            freq[a-1, i] += 1
            freq[b-1, i] += 1
        print(freq)

        if not np.any(freq.sum(axis=1) >= 6):
            return -1

        l_dice = (np.array(list(range(6))) + 1)[[freq.sum(axis=1) >= 6]]
        ret = 6
        for di in l_dice:
            print(di)
            ret = min(ret, min(min(A.count(di), 6 - A.count(di)), min(B.count(di), 6 - B.count(di))))
    
        return ret
        
        
        

In [77]:
A.count(2)

4

In [81]:

A = [2,1,2,4,2,2]
B = [5,2,6,2,3,2]

s = Solution()
s.minDominoRotations(A, B)



[[0. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 2.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
2


/Users/hiro/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:20: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


2

In [82]:
A = [3,5,1,2,3]
B = [3,6,3,3,4]
s = Solution()
s.minDominoRotations(A, B)


[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [2. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]


-1

In [129]:
import numpy as np
class Solution(object):
    def minDominoRotations(self, A, B):
        """
        :type A: List[int]
        :type B: List[int]
        :rtype: int
        """
        
        l_domino = len(A)
        freq = np.zeros([6,l_domino])
        for i, (a, b) in enumerate(zip(A, B)):
            freq[a-1, i] += 1
            freq[b-1, i] += 1

        if np.all(np.diff(np.array(A)) == 0) or np.all(np.diff(np.array(B)) == 0):
            return 0 
        self.freq = freq
#         if not np.any(freq.sum(axis=1) >= l_domino):
        if not np.any(np.all(s.freq >= 1, axis=1)):
            return -1

#         l_dice = (np.array(list(range(6))) + 1)[tuple([freq.sum(axis=1) >= l_domino])]
        l_dice = (np.array(list(range(6))) + 1)[tuple([np.all(s.freq >= 1, axis=1)])]
        ret = l_domino
        for di in l_dice:
            # print(di)
            ret = min(ret, min(min(A.count(di), l_domino - A.count(di)), min(B.count(di), l_domino - B.count(di))))
    
        return ret

In [130]:
A = [1,1,1,1,1,1,1,1]
B = [1,1,1,1,1,1,1,1]
s = Solution()
s.minDominoRotations(A, B)


0

In [93]:
np.all(np.diff(np.array(A)) == 0)

True

In [89]:
s.freq

array([[2., 2., 2., 2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [131]:
A = [1,2,1,1,1,2,2,2]
B = [2,1,2,2,2,2,2,2] # expected 1
s = Solution()
s.minDominoRotations(A, B)


1

In [104]:
len([1,2,1,1,1,2,2,2])

8

In [97]:
s.freq

array([[1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 2., 2., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [106]:
s.freq.sum(axis=1) > 8

array([False,  True, False, False, False, False])

In [99]:
np.any(s.freq.sum(axis=1) >= )

True

In [100]:
s.freq.sum(axis=1)

array([ 5., 11.,  0.,  0.,  0.,  0.])

In [132]:
A = [3,5,1,2,3]
B = [3,6,3,3,4]
s = Solution()
s.minDominoRotations(A, B)


-1

In [115]:
s.freq

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [2., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [116]:
s.freq.sum(axis=1)

array([1., 1., 5., 1., 1., 1.])

In [128]:
np.all(s.freq >= 1, axis=1)

array([False, False, False, False, False, False])